#pragma once

#include <QtCore/qglobal.h>

#ifndef BUILD_STATIC
# if defined(NODEATTRIBUTECONTROL_LIB)
#  define NODEATTRIBUTECONTROLSHARED_EXPORT Q_DECL_EXPORT
# else
#  define NODEATTRIBUTECONTROLSHARED_EXPORT Q_DECL_IMPORT
# endif
#else
# define NODEATTRIBUTECONTROLSHARED_EXPORT
#endif
